/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gephi.libgexf;

public class GEXF {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GEXF(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GEXF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      libgexfJNI.delete_GEXF(swigCPtr);
    }
    swigCPtr = 0;
  }

  public GEXF() {
    this(libgexfJNI.new_GEXF__SWIG_0(), true);
  }

  public GEXF(GEXF orig) {
    this(libgexfJNI.new_GEXF__SWIG_1(GEXF.getCPtr(orig), orig), true);
  }

  public UndirectedGraph getUndirectedGraph() {
    return new UndirectedGraph(libgexfJNI.GEXF_getUndirectedGraph(swigCPtr, this), false);
  }

  public DirectedGraph getDirectedGraph() {
    return new DirectedGraph(libgexfJNI.GEXF_getDirectedGraph(swigCPtr, this), false);
  }

  public void set_graph(Graph value) {
    libgexfJNI.GEXF__graph_set(swigCPtr, this, Graph.getCPtr(value), value);
  }

  public Graph get_graph() {
    long cPtr = libgexfJNI.GEXF__graph_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Graph(cPtr, false);
  }

}
