/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gephi.libgexf;

public class MessageExceptionBuilder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MessageExceptionBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MessageExceptionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      libgexfJNI.delete_MessageExceptionBuilder(swigCPtr);
    }
    swigCPtr = 0;
  }

  public static SWIGTYPE_p_std__string buildString(SWIGTYPE_p_std__string message, long node_id) {
    return new SWIGTYPE_p_std__string(libgexfJNI.MessageExceptionBuilder_buildString(SWIGTYPE_p_std__string.getCPtr(message), node_id), true);
  }

  public void abstractClass() {
    libgexfJNI.MessageExceptionBuilder_abstractClass(swigCPtr, this);
  }

}
